[package]
name = "planet_generation"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
noise = { workspace = true }
bevy-inspector-egui = { workspace = true }
common = { path = "../common" }